V22F-544 Code Coverage SDALib
red-panda-productions/SDALib pull request #17
Opened 2022-04-24 12:36 UTC by KungFuDonkey

This PR creates a code coverage report for SDALib

2022-04-25 07:30 UTC, larsdekwant requested changes
Build is failing and rename `Code Coverage.yml` file to `code-coverage.yml` to avoid any possible errors with spaces in file names

2022-04-25 10:17 UTC, suppergerrie2 requested changes

2022-04-25 10:17 UTC, suppergerrie2 commented on .github/workflows/Code Coverage.yml
> +        .\SDACoverage.bat
The file is named `coverage.bat` in IPCLib, either make this one `coverage.bat` or the other one `IPCLibCoverage.bat` for consistance

2022-04-26 08:20 UTC, larsdekwant approved these changes

2022-04-26 10:51 UTC, suppergerrie2 approved these changes

2022-04-26 10:57 UTC, merged