V22F-642 Update replay blackbox 3
red-panda-productions/SDALib pull request #20
Opened 2022-05-01 13:35 UTC by noutheesink

Replay blackbox reads binary files. Makes 4 decisions.

2022-05-01 13:38 UTC, KungFuDonkey approved these changes

2022-05-01 18:57 UTC, shoekzema requested changes
Functions ReplayDriver(), InitAI() and UpdateAI() are implemented in a header file. Should be in a .cpp file. They are also missing documentation.

2022-05-01 18:57 UTC, shoekzema commented on SDALib-CPP/SDAReplay/ReplayDriver.h
> +    return p_out.write(reinterpret_cast<const char*>(&(p_b.t)), sizeof(TYPE));
any reason why this comment is here?

2022-05-01 19:19 UTC, KungFuDonkey commented
> Functions ReplayDriver(), InitAI() and UpdateAI() are implemented in a header file. Should be in a .cpp file. They are also missing documentation.

That is not entirely true as we didn't do that in most of the files on SDALib, we can make this a bug and convert the entire library later

2022-05-02 11:29 UTC, noutheesink commented on SDALib-CPP/SDAReplay/ReplayDriver.h
> +    return p_out.write(reinterpret_cast<const char*>(&(p_b.t)), sizeof(TYPE));
Not really

2022-05-02 12:01 UTC, shoekzema approved these changes

2022-05-03 13:08 UTC, merged