V22F-906 incorrect intervention
red-panda-productions/SDALib pull request #34
Opened 2022-06-10 16:30 UTC by sjoeman1

the fix was to update the struct in SDALib, since these values got added to DAISI as well, The clientbb PR with the same ID is also needed for this

2022-06-10 16:49 UTC, shoekzema requested changes

2022-06-10 16:49 UTC, shoekzema commented on SDALib-CPP/SpeedDreams/SDStructs.hpp
> +    tdble Time;                 /**< Estimated time in seconds */
```suggestion
    float length;               /**< Length in meters of the middle of the track */
    /// SIMULATED DRIVING ASSISTANCE: added tdble Time
    tdble Time;                 /**< Estimated time in seconds */
```

2022-06-10 16:49 UTC, shoekzema commented on SDALib-CPP/SpeedDreams/SDStructs.hpp
>      t3Dd		min;
```suggestion
    tdble Time;       /**< main track time (estimated) */

    t3Dd		min;
```

2022-06-12 08:48 UTC, shoekzema approved these changes

2022-06-12 12:48 UTC, noutheesink approved these changes

2022-06-12 13:17 UTC, noutheesink commented
Merging with Sjoerd's permission

2022-06-12 13:17 UTC, merged